package com.ospchat.shared.net.dto

import kotlinx.serialization.Serializable

/*
 * Wire schemas for the audio-call signaling routes under /v1/call/.
 *
 * All four messages carry a callId (UUID generated by the caller when the
 * call starts; both peers reference the same id for every subsequent message)
 * plus the sender's stable fromUuid for the standard
 * verifiedPeerOrRespond authentication check.
 *
 * Media itself never flows through these endpoints — only SDP / ICE. The
 * actual audio rides UDP via libwebrtc once ICE has connected. ICE gathering
 * is restricted to host candidates (LAN-only); no STUN, no TURN.
 */

/** `POST /v1/call/offer` — caller invites callee to a new audio call. */
@Serializable
data class CallOfferDto(
    val callId: String,
    val fromUuid: String,
    val fromNickname: String,
    val sdp: String,
    val sentAt: Long,
)

/** `POST /v1/call/answer` — callee accepts the offer; carries the answer SDP. */
@Serializable
data class CallAnswerDto(
    val callId: String,
    val fromUuid: String,
    val sdp: String,
)

/**
 * `POST /v1/call/ice` — trickle ICE candidate from either side. Sent zero or
 * more times during negotiation; receivers add each candidate to the live
 * `RTCPeerConnection`.
 */
@Serializable
data class CallIceDto(
    val callId: String,
    val fromUuid: String,
    val candidate: String,
    val sdpMid: String? = null,
    val sdpMLineIndex: Int = 0,
)

/**
 * `POST /v1/call/hangup` — either side ends the call. Same wire shape covers:
 *   - **rejecting an incoming call** (callee POSTs hangup while still RINGING),
 *   - **cancelling an outgoing call** (caller POSTs hangup before answer),
 *   - **ending a connected call** (either side, normal termination),
 *   - **busy-rejecting an incoming call** (callee already on another call).
 *
 * The receiver derives the meaning from its own local call state; the
 * optional [reason] is purely informational, used by the history UI.
 */
@Serializable
data class CallHangupDto(
    val callId: String,
    val fromUuid: String,
    val reason: String? = null,
)
