package com.ospchat.shared.net.dto

import com.ospchat.shared.crypto.SignaturePayloadBuilder
import kotlinx.serialization.Serializable

/*
 * Wire schemas for the audio-call signaling routes under /v1/call/.
 *
 * All four messages carry a callId (UUID generated by the caller when the
 * call starts; both peers reference the same id for every subsequent message)
 * plus the sender's stable fromUuid for the standard
 * verifiedPeerOrRespond authentication check.
 *
 * Phase 3 multi-network bridging: every DTO now carries optional
 * `signedAt` + `signature` fields (same pattern as the phase-2b signed DTOs
 * — see [com.ospchat.shared.crypto.SignaturePayloadBuilder]). Receivers run
 * the standard `verifySignatureOrTolerate` check; null fields trigger the
 * tolerate-unsigned rollout path that keeps pre-phase-3 peers inter-operable.
 *
 * Media itself never flows through these endpoints — only SDP / ICE. Audio
 * rides UDP via libwebrtc once ICE has connected. Phase 3 introduces the
 * `/v1/call/relay-cred` endpoint that issues short-lived TURN credentials so
 * libwebrtc can also gather relayed candidates when peers can't reach each
 * other directly.
 */

/**
 * `POST /v1/call/offer` — caller invites callee to a new audio call.
 *
 * Phase 5 multi-network bridging: `toUuid` / `via` / `hopTtl` enable
 * relayed signaling through bridge peers, mirroring the phase-4 pattern
 * for message DTOs. When the originator and target can't reach each
 * other directly, the originator POSTs to a relay-enabled bridge with
 * `toUuid` set to the final target's UUID; the bridge sees
 * `toUuid != self`, appends itself to `via`, decrements `hopTtl`, and
 * forwards. The signature commits `toUuid` (append-only over the
 * phase-3 payload) so the target can verify the originator's identity
 * regardless of how many hops the offer took.
 */
@Serializable
data class CallOfferDto(
    val callId: String,
    val fromUuid: String,
    val fromNickname: String,
    val sdp: String,
    val sentAt: Long,
    val signedAt: Long? = null,
    val signature: String? = null,
    val toUuid: String? = null,
    val via: List<String>? = null,
    val hopTtl: Int? = null,
)

/** `POST /v1/call/answer` — callee accepts the offer; carries the answer SDP. */
@Serializable
data class CallAnswerDto(
    val callId: String,
    val fromUuid: String,
    val sdp: String,
    val signedAt: Long? = null,
    val signature: String? = null,
    val toUuid: String? = null,
    val via: List<String>? = null,
    val hopTtl: Int? = null,
)

/**
 * `POST /v1/call/ice` — trickle ICE candidate from either side. Sent zero or
 * more times during negotiation; receivers add each candidate to the live
 * `RTCPeerConnection`.
 */
@Serializable
data class CallIceDto(
    val callId: String,
    val fromUuid: String,
    val candidate: String,
    val sdpMid: String? = null,
    val sdpMLineIndex: Int = 0,
    val signedAt: Long? = null,
    val signature: String? = null,
    val toUuid: String? = null,
    val via: List<String>? = null,
    val hopTtl: Int? = null,
)

/**
 * `POST /v1/call/hangup` — either side ends the call. Same wire shape covers:
 *   - **rejecting an incoming call** (callee POSTs hangup while still RINGING),
 *   - **cancelling an outgoing call** (caller POSTs hangup before answer),
 *   - **ending a connected call** (either side, normal termination),
 *   - **busy-rejecting an incoming call** (callee already on another call).
 *
 * The receiver derives the meaning from its own local call state; the
 * optional [reason] is purely informational, used by the history UI.
 */
@Serializable
data class CallHangupDto(
    val callId: String,
    val fromUuid: String,
    val reason: String? = null,
    val signedAt: Long? = null,
    val signature: String? = null,
    val toUuid: String? = null,
    val via: List<String>? = null,
    val hopTtl: Int? = null,
)

/**
 * `POST /v1/call/relay-cred` — request short-lived TURN credentials from a
 * relay-enabled bridge so libwebrtc can gather relay-class ICE candidates.
 * Phase 3 multi-network bridging.
 *
 * The bridge issues credentials valid for 5 minutes (matching the existing
 * signature replay window) bound to the requesting peer's UUID — the username
 * encodes the expiry timestamp so the TURN server can verify statelessly
 * (RFC 8155 / TURN-REST-API style).
 */
@Serializable
data class RelayCredRequestDto(
    val fromUuid: String,
    val requestedAt: Long,
    val signedAt: Long? = null,
    val signature: String? = null,
)

/**
 * Response to `POST /v1/call/relay-cred`. The bridge signs this so the
 * requester can verify the credentials weren't forged in transit by a peer
 * that hijacked the LAN response.
 *
 * `uris` lists one TURN URI per externally-routable interface the bridge is
 * bound to; the requester adds them all to its `RTCConfiguration.iceServers`
 * and libwebrtc picks whichever ICE pair wins.
 */
@Serializable
data class RelayCredResponseDto(
    val fromUuid: String,
    val uris: List<String>,
    val username: String,
    val credential: String,
    val expiresAt: Long,
    val signedAt: Long? = null,
    val signature: String? = null,
)

// ---- Signature payload extensions ------------------------------------------

internal fun CallOfferDto.signaturePayload(signedAt: Long): ByteArray {
    val b =
        SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.CALL_OFFER)
            .writeString(callId)
            .writeString(fromUuid)
            .writeString(fromNickname)
            .writeString(sdp)
            .writeLong(sentAt)
            .writeLong(signedAt)
    // Phase 5 append-only: pre-PR-3 originators (toUuid==null) skip this,
    // so their payload is byte-identical to phase-3. PR-3+ originators
    // signing a relayed offer commit toUuid into the signature so the
    // target can verify their identity regardless of how the offer hopped.
    if (toUuid != null) b.writeNullableString(toUuid)
    return b.build()
}

internal fun CallAnswerDto.signaturePayload(signedAt: Long): ByteArray {
    val b =
        SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.CALL_ANSWER)
            .writeString(callId)
            .writeString(fromUuid)
            .writeString(sdp)
            .writeLong(signedAt)
    if (toUuid != null) b.writeNullableString(toUuid)
    return b.build()
}

internal fun CallIceDto.signaturePayload(signedAt: Long): ByteArray {
    val b =
        SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.CALL_ICE)
            .writeString(callId)
            .writeString(fromUuid)
            .writeString(candidate)
            .writeNullableString(sdpMid)
            .writeInt(sdpMLineIndex)
            .writeLong(signedAt)
    if (toUuid != null) b.writeNullableString(toUuid)
    return b.build()
}

internal fun CallHangupDto.signaturePayload(signedAt: Long): ByteArray {
    val b =
        SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.CALL_HANGUP)
            .writeString(callId)
            .writeString(fromUuid)
            .writeNullableString(reason)
            .writeLong(signedAt)
    if (toUuid != null) b.writeNullableString(toUuid)
    return b.build()
}

internal fun RelayCredRequestDto.signaturePayload(signedAt: Long): ByteArray =
    SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.RELAY_CRED_REQUEST)
        .writeString(fromUuid)
        .writeLong(requestedAt)
        .writeLong(signedAt)
        .build()

internal fun RelayCredResponseDto.signaturePayload(signedAt: Long): ByteArray =
    SignaturePayloadBuilder(com.ospchat.shared.crypto.SignatureDomain.RELAY_CRED_RESPONSE)
        .writeString(fromUuid)
        .writeList(uris) { writeString(it) }
        .writeString(username)
        .writeString(credential)
        .writeLong(expiresAt)
        .writeLong(signedAt)
        .build()
